# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jessica Temporal
email: jessicatemporal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Data Scientist, Podcaster @ Pizza de Dados, Lecturer and Developer. my pronouns are she/her/hers.
  This is my personal blog, my opinions are my own.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

#sidebar
default-image: channel-cover.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

reading_time:       true
words_per_minute: 200

#footer

built-by: jtemporal

copyright:
   name: jtemporal
   link: 'https://jtemporal.com'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 21
paginate_path: /page:num/

# Tracker
analytics:
tagmanager:

#social
twitter: http://twitter.com/jesstemporal
github: http://github.com/jtemporal
email: jessicatemporal@gmail.com

# Collections
collections:
  - hacktoberfest_projects

# Sass style
sass:
  style: compressed

# Include list
include: [.well-known, EnJtResume.pdf, folium]

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag]
